### Sample queries
# list 10 products
# list 10 customers
# most in demand products
# list all product names and ids of products ordered by customers in NY state
# list all product names, ids, total quanity of products ordered by customers in NY state in desceding order of total quantity
# list of customers who order most number of products in decending order 
# list all product names and ids of products ordered by customers in New york state.
# list top selling products by state
# list top selling products by customer
# top 10 customers
# list all orders placed on 3rd august 2019
# select all products brought by customer Tammie Crylen
# name of the products sold most in Utah and Newyork
# number of latest orders for each customers in the decending order
# list products brought by 'digital lifestyle solutions', using lower case for comparison
# who are my most valuable( top 3) customers
# list most products sold in New york and Utah
# list most products sold in Utah, include state code in the output
# list products brought by 'John M Wozniak'
# list products brought by 'Henry M Boylan'
# list products brought by 'Patrick J Hassett'

###Durable function orchastrator invocation
POST {{funcUrl}}/api/orchestrators/fn-drbl-orch-openai-sql?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "query": "list most products sold in New york and Utah"   
}

###regular(non durable) function invocation. 
POST {{funcUrl}}/api/fn-openai-sql?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "query": "select all products brought by digital life solutions, using lower case for comparison"
}


